"""Workflow integration tests (Phase C16).

The stop condition: one reel generated by the Workflow Engine automatically PASSES
the Quality Checker. Hermetic — the default pipeline uses the mock storyboard/voice
providers and the mock renderer, so no GPU/ffmpeg/network is touched.
"""
from __future__ import annotations

import pytest

from workflow_engine import WorkflowEngine

from quality_engine.checker.report import CheckStatus
from quality_engine.workflow_link import artifacts_from_result, check_workflow_result


@pytest.fixture
def workflow_result(tmp_path):
    engine = WorkflowEngine(root=tmp_path / "run_root")
    workflow = engine.build("Why investing in real estate early is beneficial",
                            template="real_estate", renderer="mock",
                            profiles=("reel_9x16", "square_1x1"))
    result = engine.run(workflow, run_id="run")
    assert result.ok
    return result


def test_generated_reel_passes_quality_check(workflow_result):
    report = check_workflow_result(workflow_result)
    assert report.ok and report.overall is CheckStatus.PASS
    # the full pipeline enables captions, branding, music, voice and an avatar plan
    assert not report.warnings
    assert not report.failures
    assert all(c.status is CheckStatus.PASS for c in report.checks)


def test_artifacts_extracted_from_result(workflow_result):
    art = artifacts_from_result(workflow_result)
    assert art.master_path.exists()
    assert art.timeline is not None and art.timeline.has_music
    assert art.voice_clips and all(p.exists() for p in art.voice_clips)
    assert art.avatar is not None and art.avatar.get("enabled")
    assert {e.profile for e in art.exports} == {"reel_9x16", "square_1x1"}


def test_report_json_serializable(workflow_result):
    import json
    report = check_workflow_result(workflow_result)
    text = json.dumps(report.to_dict())
    assert '"overall": "pass"' in text or '"overall":"pass"' in text
